name: Deploy to Server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: executing remote ssh commands using ssh key and passphrase
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.ARTIFACT_SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ${{ secrets.APP_PATH }}
            git fetch origin
            git reset --hard origin/master
            cd ..
            docker-compose up -d --build ${{ secrets.APP_NAME }}
            exit
            


